apiVersion: apps/v1
kind: Deployment

metadata:
  name: myas-clicker-deployment
  labels:
    app: myas-clicker

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myas-clicker
  template:
    metadata:
      name: myas-clicker
      labels:
        app: myas-clicker

    spec:
      containers:
        - name: myas-clicker
          image: pikokr/myas-clicker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/data
              name: data
          livenessProbe:
            httpGet:
              port: 8080
              path: /
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service

metadata:
  name: myas-clicker

spec:
  selector:
    app: myas-clicker
  ports:
    - port: 8080
      protocol: TCP
